In [1]:
import numpy as np


In [2]:
n2=np.array([[1,2,3],[2,3,4]])
print(n2)
print(n2.shape)

[[1 2 3]
 [2 3 4]]
(2, 3)


In [3]:
x=np.random.randint(1,10,(3,2))
y=np.random.randint(1,10,(3,2))
print(x)
print(y)

[[3 6]
 [2 5]
 [5 9]]
[[1 2]
 [6 1]
 [3 7]]


In [4]:
x+y

array([[ 4,  8],
       [ 8,  6],
       [ 8, 16]])

In [5]:
np.sin(x)

array([[ 0.14112001, -0.2794155 ],
       [ 0.90929743, -0.95892427],
       [-0.95892427,  0.41211849]])

In [6]:
print(x.sum())
print(x.mean())
print(x.std())

30
5.0
2.23606797749979


In [10]:
a=np.linspace(0,5,50)
print(a.shape)
a2=a.reshape(10,5)
print(a2)

(50,)
[[0.         0.10204082 0.20408163 0.30612245 0.40816327]
 [0.51020408 0.6122449  0.71428571 0.81632653 0.91836735]
 [1.02040816 1.12244898 1.2244898  1.32653061 1.42857143]
 [1.53061224 1.63265306 1.73469388 1.83673469 1.93877551]
 [2.04081633 2.14285714 2.24489796 2.34693878 2.44897959]
 [2.55102041 2.65306122 2.75510204 2.85714286 2.95918367]
 [3.06122449 3.16326531 3.26530612 3.36734694 3.46938776]
 [3.57142857 3.67346939 3.7755102  3.87755102 3.97959184]
 [4.08163265 4.18367347 4.28571429 4.3877551  4.48979592]
 [4.59183673 4.69387755 4.79591837 4.89795918 5.        ]]


In [13]:
x=np.random.randint(1,10,(10,10))
print(x)

[[3 7 4 7 1 5 2 4 6 1]
 [9 7 2 7 3 6 6 8 8 9]
 [7 2 1 5 9 4 4 9 3 6]
 [8 1 9 4 3 7 5 6 7 8]
 [3 4 3 8 8 1 2 3 2 7]
 [7 6 7 3 4 6 5 5 9 8]
 [4 1 9 5 7 1 6 3 9 5]
 [7 1 2 9 2 5 7 2 6 4]
 [8 1 3 7 1 4 7 7 8 3]
 [7 4 4 3 8 9 8 9 5 6]]


In [16]:
print(x[0,0])
print(x[0,-1])

3
1


In [20]:
print(x[0])
print(x[1])
print(x[-1])
print(x[:3])
print(x[-3:])

[3 7 4 7 1 5 2 4 6 1]
[9 7 2 7 3 6 6 8 8 9]
[7 4 4 3 8 9 8 9 5 6]
[[3 7 4 7 1 5 2 4 6 1]
 [9 7 2 7 3 6 6 8 8 9]
 [7 2 1 5 9 4 4 9 3 6]]
[[7 1 2 9 2 5 7 2 6 4]
 [8 1 3 7 1 4 7 7 8 3]
 [7 4 4 3 8 9 8 9 5 6]]


In [25]:
print(x[:,0])
print(x[:,-1])
print(x[:,:3])
print(x[:,-3:])

[3 9 7 8 3 7 4 7 8 7]
[1 9 6 8 7 8 5 4 3 6]
[[3 7 4]
 [9 7 2]
 [7 2 1]
 [8 1 9]
 [3 4 3]
 [7 6 7]
 [4 1 9]
 [7 1 2]
 [8 1 3]
 [7 4 4]]
[[4 6 1]
 [8 8 9]
 [9 3 6]
 [6 7 8]
 [3 2 7]
 [5 9 8]
 [3 9 5]
 [2 6 4]
 [7 8 3]
 [9 5 6]]


In [26]:
print(x[:,[0,2,3,6]])

[[3 4 7 2]
 [9 2 7 6]
 [7 1 5 4]
 [8 9 4 5]
 [3 3 8 2]
 [7 7 3 5]
 [4 9 5 6]
 [7 2 9 7]
 [8 3 7 7]
 [7 4 3 8]]


filtering

In [34]:
x<5

array([[ True, False,  True, False,  True, False,  True,  True, False,
         True],
       [False, False,  True, False,  True, False, False, False, False,
        False],
       [False,  True,  True, False, False,  True,  True, False,  True,
        False],
       [False,  True, False,  True,  True, False, False, False, False,
        False],
       [ True,  True,  True, False, False,  True,  True,  True,  True,
        False],
       [False, False, False,  True,  True, False, False, False, False,
        False],
       [ True,  True, False, False, False,  True, False,  True, False,
        False],
       [False,  True,  True, False,  True, False, False,  True, False,
         True],
       [False,  True,  True, False,  True,  True, False, False, False,
         True],
       [False,  True,  True,  True, False, False, False, False, False,
        False]])

In [35]:
x[x<5]

<function ndarray.sum>

In [32]:
x[(x>3) & (x<7)]

array([4, 5, 4, 6, 6, 6, 5, 4, 4, 6, 4, 5, 6, 4, 6, 4, 6, 5, 5, 4, 5, 6,
       5, 5, 6, 4, 4, 4, 4, 5, 6])